import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    nav: {
      showroom: 'Showroom',
      configurator: 'Configurator',
      process: 'Our Process',
      projects: 'Projects',
      shop: 'Shop',
      services: 'Services',
      quoteBtn: 'Get a Quote'
    },
    hero: {
      badge: 'Premium Metal Fabrication',
      title1: 'From Custom Fabrication',
      title2: 'To Ready-to-Install Products.',
      subtitle: 'Built with precision. Designed to last. We transform raw architectural concepts into flawless metal masterpieces for residential and commercial spaces.',
      ctaPrimary: 'Configure Railing',
      ctaSecondary: 'Watch Workshop',
      statUSA: 'Made in USA',
      statUSASub: 'In-house manufacturing',
      statPrecision: '0.01mm Precision',
      statPrecisionSub: 'CNC & laser cutting',
      statWarranty: 'Lifetime Warranty',
      statWarrantySub: 'Powder-coated durability'
    },
    showroom: {
      tag: 'Inside the District',
      title: 'Our Production Hub',
      desc: 'We don’t outsource. From laser cutting to powder coating, every stage of fabrication happens under our roof in Los Angeles, California.',
      laser: 'Laser Cutting',
      laserDesc: 'Ultra-precise fiber optic lasers cutting through heavy steel, aluminum, and stainless plates with clean-cut edges.',
      welding: 'Robotic Welding',
      weldingDesc: 'High-strength structural welding combining automated robot precision with master artisan hand-finishes.',
      coating: 'Powder Coating',
      coatingDesc: 'Electrostatic powder application cured at 400°F, creating a rock-solid, weather-resistant barrier.',
      assembly: 'Final Assembly',
      assemblyDesc: 'Meticulous alignment checks, hardware integration, and quality control inspection before shipping.'
    },
    configurator: {
      tag: 'Interactive Builder',
      title: 'Configure Your Railing',
      desc: 'Design your railing system in real-time. Choose your material, finish, and dimensions for an instant estimate.',
      material: '1. Select Material',
      steel: 'Steel (Heavy Duty)',
      aluminum: 'Aluminum (Rust Proof)',
      stainless: 'Stainless Steel (Premium)',
      finish: '2. Select Finish',
      matteBlack: 'Industrial Matte Black',
      brushedSteel: 'Brushed Satin',
      bronze: 'Oil-Rubbed Bronze',
      mounting: '3. Mounting Style',
      wall: 'Wall Mounted',
      floor: 'Floor / Post Mounted',
      cable: 'Cable Railing System',
      length: '4. System Length',
      priceEst: 'Estimated Price',
      customRequest: 'Request Custom Specs',
      addToCart: 'Order Configured System',
      contactExpert: 'Talk to an Engineer',
      ft: 'ft'
    },
    process: {
      tag: 'Workflow',
      title: 'How We Deliver Excellence',
      desc: 'A seamless 5-step process from initial blueprint to final installation, built to eliminate friction.',
      step1Title: 'Design & Render',
      step1Desc: 'We take your dimensions, run engineering checks, and send a high-fidelity 3D render for approval.',
      step2Title: 'Laser & CNC Cut',
      step2Desc: 'Raw plates are laser-cut and tubes are bent using high-precision CNC machinery.',
      step3Title: 'Artisanal Welds',
      step3Desc: 'TIG and MIG welders join connections seamlessly, grinding joints to an invisible finish.',
      step4Title: 'Powder Coat Protect',
      step4Desc: 'Components are baked in our ovens for ultimate rust-protection and sleek aesthetics.',
      step5Title: 'Deliver & Install',
      step5Desc: 'We ship ready-to-install kits nationwide, or dispatch our crew for professional installation.'
    },
    showcase: {
      tag: 'Signature Catalog',
      title: 'Active Fabrication Batches',
      desc: 'Pre-engineered custom designs currently in fabrication. Select a system to load details or queue slots.',
      loadBtn: 'Configure Model',
      slotsLeft: 'Slots Left in Laser Queue',
      leadTime: 'Est. Lead Time',
      status: 'Batch Status',
      transit: 'Days Transit',
      priority: 'Priority',
      activeQueue: 'LASER QUEUE ACTIVE',
      batchesCount: 'ACTIVE BATCHES: 14',
      avgTime: 'AVG LEAD TIME: 5.2 DAYS',
      queueLoad: 'QUEUE LOAD: 84%'
    },
    beforeAfter: {
      tag: 'Transformations',
      title: 'Before & After',
      desc: 'Drag the slider to see how custom architectural metal transforms raw structures into premium spaces.',
      before: 'BEFORE',
      after: 'AFTER'
    },
    quote: {
      tag: 'Start Your Project',
      title: 'Request a Custom Quote',
      desc: 'Have blueprints, sketches, or custom dimensions? Upload them here and our engineering team will get back to you within 24 hours.',
      fullName: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      projectType: 'Project Type',
      residential: 'Residential',
      commercial: 'Commercial',
      message: 'Project Details & Dimensions',
      messagePlaceholder: 'E.g., I need a custom L-shaped handrail for a outdoor concrete stair. Length is approximately 12ft...',
      upload: 'Drag & drop blueprints, sketches or inspiration photos here, or click to browse',
      uploadSub: 'Supports PDF, DXF, DWG, PNG, JPG (Max 25MB)',
      submit: 'Submit Quote Request',
      sending: 'Submitting Details...',
      success: 'Thank you! Our engineering team is reviewing your blueprints.',
      whatsapp: 'Chat on WhatsApp',
      callUs: 'Call Now: +1 (346) 234-9640'
    },
    staircase: {
      tag: 'PREMIUM ARCHITECTURAL SYSTEM',
      title: 'The Horizon Cantilevered Staircase',
      desc: 'Engineered with floating walnut treads and structural steel supports, delivering absolute minimalism and structural safety for modern homes.',
      materialTab: '1. Material & Wood Specs',
      calculatorTab: '2. Rise & Run Calculator',
      loadTab: '3. Engineering & Load Simulator',
      faqTab: 'Safety & Code FAQ',
      reviewsTab: 'Customer Reviews',
      heightLbl: 'Floor-to-Floor Height',
      widthLbl: 'Stair Width',
      woodLbl: 'Select Wood Species',
      finishLbl: 'Steel Powder Coat Finish',
      stepsRequired: 'Steps Required',
      estRise: 'Est. Rise per Step',
      estRun: 'Est. Run per Step',
      codeCompliance: 'IRC Stair Code Compliance',
      compliant: 'Compliant',
      warning: 'Non-Compliant (Rise > 7.75")',
      woodWalnut: 'American Walnut (Rich Dark)',
      woodOak: 'Premium White Oak (Warm Natural)',
      woodMaple: 'Hard Maple (Clean Light)',
      steelMatteBlack: 'Industrial Matte Black',
      steelBrushed: 'Satin Brushed Stainless',
      metalFinish: 'Metal Finish',
      priceEst: 'Price Estimate',
      priceEstSub: 'Excluding installation & custom freight',
      ctaQuote: 'Send Specs to Quote Builder',
      loadTitle: 'Structural Load Simulation',
      loadDesc: 'Hover or tap on the steps to simulate loading weight. The cantilever design distributes force back to the heavy structural wall bracket.',
      loadStress: 'Tread Stress Level',
      loadNormal: 'Normal (0-150 lbs)',
      loadMedium: 'Medium (150-300 lbs)',
      loadMax: 'High Stress (300-400 lbs)',
      downloadSpecs: 'Download CAD Blueprint & Specs',
      downloadPdf: 'Download PDF Installation Guide',
      faq1Q: 'Are floating stairs safe?',
      faq1A: 'Yes. Horizon systems are engineered to exceed IRC requirements. Treads are supported by a heavy-duty steel channel anchored directly into structural wall framing.',
      faq2Q: 'What is the standard lead time?',
      faq2A: 'Each system is engineered and custom-cut to your dimensions. Fabrication takes 3-4 weeks, followed by flatbed freight delivery.',
      faq3Q: 'Do they comply with local building codes?',
      faq3A: 'Our rise and run calculator flags structural adjustments to ensure compliance with the International Residential Code (IRC), including maximum 7.75" rise and minimum 10" run.',
      review1Author: 'Marcus K. (Architect)',
      review1Text: 'The engineering on the Horizon staircase is impeccable. The structural channel was easy to incorporate during framing, and the wood treads are beautiful.',
      review2Author: 'Elena R. (Homeowner)',
      review2Text: 'Stunning centerpiece in our foyer. It feels rock-solid underfoot, with absolutely zero bounce or wobble. Exceptional quality.'
    },
    shop: {
      title: 'Architectural Catalog',
      desc: 'Browse our signature pre-engineered systems and custom parts, precision manufactured under one roof in Los Angeles.',
      searchPlaceholder: 'Search products (e.g. cable, glass, gates)...',
      all: 'All Products',
      stairs: 'Staircases',
      railings: 'Railings',
      handrails: 'Handrails',
      gates: 'Gates',
      fences: 'Fences',
      accessories: 'Accessories & Parts',
      filters: 'Filters',
      category: 'Category',
      material: 'Material',
      priceRange: 'Price Range',
      steel: 'Carbon Steel',
      stainless: 'Stainless Steel',
      aluminum: 'Aluminum',
      timber: 'Hardwood',
      noProducts: 'No products found matching active filters.',
      viewProduct: 'Configure Product',
      perFt: '/ft',
      unit: '/unit'
    },
    services: {
      title: 'Architectural Fabrication Services',
      subtitle: 'Precision metal design and structural fabrication, engineered to code and built to last.',
      staircases: 'Staircase Systems',
      railings: 'Railing Systems',
      handrails: 'ADA Handrails',
      gatesFences: 'Gates & Fences',
      customFab: 'Custom Fabrication',
      processTitle: 'Custom Fabrication Process',
      specsMatrix: 'Material & Capability Standards',
      tolerance: 'Tolerances',
      weldingCert: 'Welding Standards',
      loadTolerance: 'Load Standards',
      ctaTitle: 'Have a Custom Blueprint?',
      ctaDesc: 'Upload your specifications directly into our architectural config tool for a certified bid.',
      ctaBtn: 'Configure Custom Order',
      viewDetails: 'View Details & Code Compliance',
      materialsUsed: 'Materials & Tolerances',
      installTitle: 'Nationwide Freight Staging & Installation',
      complianceCheck: 'Compliance Checks'
    },
    footer: {
      slogan: 'Precision in every detail. Built for modern living.',
      address: '1420 Station Metalworks Way, Los Angeles, CA 90021',
      rights: 'All rights reserved.'
    }
  },
  es: {
    nav: {
      showroom: 'Showroom',
      configurator: 'Configurador',
      process: 'Nuestro Proceso',
      projects: 'Proyectos',
      shop: 'Tienda',
      services: 'Servicios',
      quoteBtn: 'Cotizar Proyecto'
    },
    hero: {
      badge: 'Fabricación Metálica Premium',
      title1: 'De Fabricación a Medida',
      title2: 'A Productos Listos para Instalar.',
      subtitle: 'Construido con precisión. Diseñado para durar. Transformamos conceptos arquitectónicos en piezas metálicas impecables para espacios residenciales y comerciales.',
      ctaPrimary: 'Configurar Barandal',
      ctaSecondary: 'Ver Taller',
      statUSA: 'Hecho en EE. UU.',
      statUSASub: 'Fabricación en taller propio',
      statPrecision: 'Precisión de 0.01mm',
      statPrecisionSub: 'Corte CNC y láser',
      statWarranty: 'Garantía de por Vida',
      statWarrantySub: 'Acabado en polvo horneado'
    },
    showroom: {
      tag: 'Dentro del Distrito',
      title: 'Nuestro Centro de Producción',
      desc: 'No subcontratamos. Desde el corte láser hasta el recubrimiento en polvo, cada etapa de la fabricación ocurre bajo nuestro techo en Los Ángeles, California.',
      laser: 'Corte Láser',
      laserDesc: 'Láseres de fibra óptica ultra precisos que cortan placas gruesas de acero, aluminio y acero inoxidable con bordes limpios.',
      welding: 'Soldadura Robótica',
      weldingDesc: 'Soldadura estructural de alta resistencia que combina la precisión de robots automatizados con acabados artesanales a mano.',
      coating: 'Pintura en Polvo',
      coatingDesc: 'Aplicación electrostática de pintura en polvo curada a 200°C (400°F), creando una barrera sólida y resistente al clima.',
      assembly: 'Ensamble Final',
      assemblyDesc: 'Meticulosas pruebas de alineación, integración de herrajes y control de calidad antes del envío.'
    },
    configurator: {
      tag: 'Constructor Interactivo',
      title: 'Configura tu Barandal',
      desc: 'Diseña tu sistema de barandal en tiempo real. Selecciona materiales, acabados y medidas para obtener un presupuesto instantáneo.',
      material: '1. Selecciona Material',
      steel: 'Acero (Máxima Resistencia)',
      aluminum: 'Aluminio (Antioxidante)',
      stainless: 'Acero Inoxidable (Premium)',
      finish: '2. Selecciona Acabado',
      matteBlack: 'Negro Mate Industrial',
      brushedSteel: 'Satín Cepillado',
      bronze: 'Bronce Pulido con Aceite',
      mounting: '3. Tipo de Montaje',
      wall: 'Montado a Muro',
      floor: 'Montado a Piso (Postes)',
      cable: 'Sistema de Barandal de Cable',
      length: '4. Longitud del Sistema',
      priceEst: 'Precio Estimado',
      customRequest: 'Solicitar Especificaciones Especiales',
      addToCart: 'Comprar Sistema Configurado',
      contactExpert: 'Hablar con un Ingeniero',
      ft: 'pies'
    },
    process: {
      tag: 'Flujo de Trabajo',
      title: 'Cómo Entregamos la Excelencia',
      desc: 'Un proceso continuo de 5 pasos desde el plano inicial hasta la instalación final, diseñado para eliminar fricciones.',
      step1Title: 'Diseño y Render',
      step1Desc: 'Tomamos tus medidas, realizamos análisis de ingeniería y te enviamos un render 3D de alta fidelidad para aprobación.',
      step2Title: 'Corte Láser y CNC',
      step2Desc: 'Las placas se cortan con láser y los tubos se doblan en maquinaria CNC de alta precisión.',
      step3Title: 'Soldaduras Artesanales',
      step3Desc: 'Soldadores TIG y MIG unen las conexiones limpiamente, puliendo las juntas para un acabado invisible.',
      step4Title: 'Pintura y Horno',
      step4Desc: 'Las piezas se hornean para ofrecer la máxima protección contra la corrosión y una estética impecable.',
      step5Title: 'Envío e Instalación',
      step5Desc: 'Enviamos kits listos para instalar a todo el país o enviamos a nuestro equipo para instalación profesional.'
    },
    showcase: {
      tag: 'Catálogo de Firma',
      title: 'Lotes de Fabricación Activos',
      desc: 'Diseños de barandal insignia actualmente en fabricación en nuestro taller. Selecciona un modelo para cargar en el configurador o apartar cupos.',
      loadBtn: 'Configurar Modelo',
      slotsLeft: 'Cupos libres en Cola de Corte',
      leadTime: 'Tiempo estimado',
      status: 'Estado del lote',
      transit: 'Días de envío',
      priority: 'Prioridad',
      activeQueue: 'COLA LÁSER ACTIVA',
      batchesCount: 'LOTES ACTIVOS: 14',
      avgTime: 'TIEMPO PROM: 5.2 DÍAS',
      queueLoad: 'CARGA DE COLA: 84%'
    },
    beforeAfter: {
      tag: 'Transformaciones',
      title: 'Antes y Después',
      desc: 'Arrastra el control deslizante para ver cómo el metal arquitectónico personalizado transforma estructuras básicas en espacios de lujo.',
      before: 'ANTES',
      after: 'DESPUÉS'
    },
    quote: {
      tag: 'Inicia tu Proyecto',
      title: 'Solicita una Cotización Especial',
      desc: '¿Tienes planos, bocetos o medidas personalizadas? Súbelos aquí y nuestro equipo de ingeniería te responderá en menos de 24 horas.',
      fullName: 'Nombre Completo',
      email: 'Correo Electrónico',
      phone: 'Número de Teléfono',
      projectType: 'Tipo de Proyecto',
      residential: 'Residencial',
      commercial: 'Comercial',
      message: 'Detalles del Proyecto y Dimensiones',
      messagePlaceholder: 'Ej. Necesito un barandal a medida en forma de L para una escalera exterior de concreto. La longitud aproximada es de 12 pies...',
      upload: 'Arrastra y suelta tus planos, bocetos o fotos aquí, o haz clic para buscar',
      uploadSub: 'Formatos soportados: PDF, DXF, DWG, PNG, JPG (Máx 25MB)',
      submit: 'Enviar Solicitud de Cotización',
      sending: 'Enviando detalles...',
      success: '¡Gracias! Nuestro equipo de ingeniería está revisando tus planos.',
      whatsapp: 'Chatear por WhatsApp',
      callUs: 'Llámanos: +1 (346) 234-9640'
    },
    staircase: {
      tag: 'SISTEMA ARQUITECTÓNICO PREMIUM',
      title: 'Escalera Flotante Horizon en Cantilever',
      desc: 'Diseñada con peldaños flotantes de nogal y soportes de acero estructural, brindando un minimalismo absoluto y seguridad estructural para hogares modernos.',
      materialTab: '1. Materiales y Madera',
      calculatorTab: '2. Calculadora de Huella',
      loadTab: '3. Simulador de Carga',
      faqTab: 'Preguntas Frecuentes',
      reviewsTab: 'Opiniones',
      heightLbl: 'Altura Suelo a Suelo',
      widthLbl: 'Ancho de Escalera',
      woodLbl: 'Especie de Madera',
      finishLbl: 'Acabado en Polvo del Acero',
      stepsRequired: 'Escalones Requeridos',
      estRise: 'Contrahuella Est. (Rise)',
      estRun: 'Huella Est. (Run)',
      codeCompliance: 'Cumplimiento Código IRC',
      compliant: 'Conforme',
      warning: 'No Conforme (Altura > 7.75")',
      woodWalnut: 'Nogal Americano (Oscuro Rico)',
      woodOak: 'Roble Blanco Premium (Cálido Natural)',
      woodMaple: 'Arce Duro (Claro Limpio)',
      steelMatteBlack: 'Negro Mate Industrial',
      steelBrushed: 'Acero Inoxidable Cepillado',
      metalFinish: 'Acabado Metálico',
      priceEst: 'Precio Estimado',
      priceEstSub: 'Excluye instalación y flete especial',
      ctaQuote: 'Enviar Especificaciones a Cotización',
      loadTitle: 'Simulación de Carga Estructural',
      loadDesc: 'Pasa el cursor o presiona los peldaños para simular el peso de carga. El diseño en cantilever distribuye la fuerza hacia el soporte de muro reforzado.',
      loadStress: 'Nivel de Tensión del Peldaño',
      loadNormal: 'Normal (0-150 lbs)',
      loadMedium: 'Medio (150-300 lbs)',
      loadMax: 'Tensión Alta (300-400 lbs)',
      downloadSpecs: 'Descargar Plano CAD y Ficha',
      downloadPdf: 'Descargar Guía de Instalación PDF',
      faq1Q: '¿Son seguras las escaleras flotantes?',
      faq1A: 'Sí. Los sistemas Horizon están diseñados para superar los requisitos de IRC. Los peldaños se soportan en un canal de acero anclado a la estructura del muro.',
      faq2Q: '¿Cuál es el tiempo de entrega estándar?',
      faq2A: 'Cada sistema se fabrica a la medida de tus dimensiones. La fabricación toma de 3 a 4 semanas, seguida del envío en transporte especial.',
      faq3Q: '¿Cumplen con los códigos de edificación locales?',
      faq3A: 'Nuestra calculadora de huella e inclinación te advierte de ajustes para asegurar cumplimiento con el Código Residencial Internacional (IRC), incluyendo huella mín. de 10" y contrahuella máx. de 7.75".',
      review1Author: 'Marcus K. (Arquitecto)',
      review1Text: 'La ingeniería en la escalera Horizon es impecable. El canal estructural fue fácil de incorporar en la obra y los peldaños de madera son preciosos.',
      review2Author: 'Elena R. (Propietaria)',
      review2Text: 'Una pieza central espectacular en nuestro vestíbulo. Se siente sólida al pisar, sin rebote alguno. Calidad excepcional.'
    },
    shop: {
      title: 'Catálogo Arquitectónico',
      desc: 'Explora nuestros sistemas pre-diseñados y piezas a medida, fabricados con precisión bajo un mismo techo en Los Ángeles.',
      searchPlaceholder: 'Buscar productos (ej. cable, vidrio, portón)...',
      all: 'Todos los productos',
      stairs: 'Escaleras',
      railings: 'Barandales',
      handrails: 'Pasamanos',
      gates: 'Portones',
      fences: 'Cercas',
      accessories: 'Accesorios y Refacciones',
      filters: 'Filtros',
      category: 'Categoría',
      material: 'Material',
      priceRange: 'Rango de Precios',
      steel: 'Acero al Carbón',
      stainless: 'Acero Inoxidable',
      aluminum: 'Aluminio',
      timber: 'Madera Dura',
      noProducts: 'No se encontraron productos con los filtros activos.',
      viewProduct: 'Configurar Producto',
      perFt: '/pie',
      unit: '/unidad'
    },
    services: {
      title: 'Servicios de Fabricación Arquitectónica',
      subtitle: 'Diseño de precisión y fabricación estructural en metal, calculados bajo norma y construidos para durar.',
      staircases: 'Sistemas de Escaleras',
      railings: 'Sistemas de Barandales',
      handrails: 'Pasamanos ADA',
      gatesFences: 'Portones y Cercas',
      customFab: 'Fabricación a Medida',
      processTitle: 'Proceso de Fabricación a Medida',
      specsMatrix: 'Estándares de Materiales y Capacidades',
      tolerance: 'Tolerancias',
      weldingCert: 'Normativa de Soldadura',
      loadTolerance: 'Soporte de Carga',
      ctaTitle: '¿Tienes un Plano Personalizado?',
      ctaDesc: 'Sube tus especificaciones a nuestro cotizador para recibir una propuesta estructurada.',
      ctaBtn: 'Configurar Pedido a Medida',
      viewDetails: 'Ver Detalles y Normativas',
      materialsUsed: 'Materiales y Tolerancias',
      installTitle: 'Logística de Envío Nacional e Instalación',
      complianceCheck: 'Verificación de Normativa'
    },
    footer: {
      slogan: 'Precisión en cada detalle. Construido para la vida moderna.',
      address: '1420 Station Metalworks Way, Los Ángeles, CA 90021',
      rights: 'Todos los derechos reservados.'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'es' : 'en'));
  };

  const t = (path) => {
    const keys = path.split('.');
    let value = translations[language];
    for (const key of keys) {
      if (!value || !value[key]) return path;
      value = value[key];
    }
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
